# Generated by Django 4.0.6 on 2022-08-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipement',
            name='ismaintenu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipement',
            name='issupporte',
            field=models.BooleanField(default=False),
        ),
    ]
